### ISSUE TITLE
Breaks under requests 2.11

### ISSUE THREAD

**Issue by Wooble** [patrys/httmock#45]
Under requests version 2.11.1, mocks are failing [like this](https://travis-ci.org/pitthsls/pycounter/jobs/156529138)

It appears that requests's prepare_request API changed?

**Comment by Wooble** [comment]
Apologies; my analysis seems to be incorrect. It's not the mock that's breaking, it's my library.

**Comment by patrys** [comment]
Yes, it seems the problem is here: https://github.com/pitthsls/pycounter/blob/master/pycounter/sushi.py#L94

No worries though! 😄

**Comment by Wooble** [comment]
I managed to get the idea in my head that since I was mocking the request, code inside requests shouldn't have been running at all. Sourcediving into how httmock works made it obvious that was a misconception. :)
