### ISSUE TITLE
Python 3.5?

### ISSUE THREAD

**Issue by meuseky** [patrys/httmock#51]
I was just wondering if this project is Python 3.5 compliant?

**Comment by thurask** [comment]
With the test suite I use this with, it works with Python 3,2-3.6, although that's not the same as completely working with 3.5/3.6.

Regardless, running the test suite on Windows 10 x64, Python 3.6.1:

```
>python tests.py
..............tests.py:336: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals(facebook_mock_count.call['count'], 4)
..............
----------------------------------------------------------------------
Ran 28 tests in 0.228s

OK
```

**Comment by patrys** [comment]
It is.
